[tox]
requires = tox-uv>=1
envlist = py311,py312

[testenv]
runner = uv-venv-lock-runner
allowlist_externals =
    docker
    docker-compose
passenv =
    SSH_AUTH_SOCK
    SKIP
commands =
    docker/pre_commit_init.sh
    pytest --junitxml=pytest-{envname}.xml tests/
    # if prek does not run these (or you don't run prek here) enable at least these checks
    # mypy src tests
    # pylint src tests
    # bandit --skip=B101 -r src
