on:
    pull_request:

jobs:
  versiontag:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - uses: actions/checkout@v6
      - name: Check version tag
        run: |
          curl -f https://raw.githubusercontent.com/pvarki/python-matrix-rmapi/main/pyproject.toml -o /tmp/main_pyproject.toml || touch /tmp/main_pyproject.toml
          grep "version = " pyproject.toml >/tmp/version.txt
          grep "version = " /tmp/main_pyproject.toml >/tmp/main_version.txt
          diff /tmp/main_version.txt /tmp/version.txt && exit 1 || exit 0

  test:
    runs-on: arc-runner-set
    permissions:
      contents: write
      pull-requests: write
      checks: write
    strategy:
      matrix:
        python-version: ["3.11"] # , "3.12"]
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: pvarki/config-ci-library/.github/actions/setup-python@main
        with:
          python-version: ${{ matrix.python-version }}
      - name: Do pre-commit checks (black, lint, mypy)
        run: |
          uv run docker/pre_commit_init.sh
      - name: Test with pytest
        env:
          SYNAPSE_REGISTRATION_SECRET: "ci-test-secret"  # pragma: allowlist secret
        run: |
          uv run py.test -v --junitxml=pytest.xml
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/pytest*.xml'
          detailed_summary: true
          check_name: 'JUnit report (local)'

  docker_builds:
    runs-on: arc-runner-set
    steps:
      - uses: actions/checkout@v6
      - name: Build test target
        run: docker build --target test -t matrixrmapi:test .
      - name: Build production target
        run: docker build --target production -t matrixrmapi:production .

  snyk-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pvarki/config-ci-library/.github/actions/setup-python@main
      - uses: pvarki/config-ci-library/.github/actions/snyk-test@main
        with:
          snyk-org: deployapp-products
          snyk-token: ${{ secrets.SNYK_TOKEN }}

  publish:
    needs: [versiontag, test, snyk-test, docker_builds]
    runs-on: arc-runner-set
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Publish Docker image
        uses: pvarki/config-ci-library/.github/actions/publish-image@main
        with:
          image-name: opendefence/matrix-integration
          dockerhub-username: ${{ vars.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          acr-repo: ${{ vars.ACR_REPO }}
          acr-username: ${{ vars.ACR_USERNAME }}
          acr-token: ${{ secrets.ACR_TOKEN }}
